-- AlterTable
ALTER TABLE `assento` MODIFY `id` INTEGER NOT NULL;

-- AlterTable
ALTER TABLE `voos` MODIFY `saida` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `chegada` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
